### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by yahnbaron** [yahnbaron/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a div to the create the background.
- [x] Creates a background pattern
- [x] fit the image to the window 
- [x] add image of the car
- [x] make car position absolute to be on top of background image
